### ISSUE TITLE
install doc: update with full steps required for activiation of starship

### ISSUE THREAD

**Issue by CoolCold** [grimoh/asdf-starship#11]
Hello!
Thanks for your work to ease install of starship with asdf!

I have question about install steps - currently readme mentions: `asdf plugin add starship` - what should happen next? I.e. for manual starship install, user is expected to update shell files to make starship work, like 
```
eval "$(starship init bash)"
```
I expect the same thing is needed here as well?

Next question - does it support to work with "local" config. i.e. per directory? I don't see how it can be done, but just in case.

Thanks in advance!

**Comment by gr1m0h** [comment]
Hello! @CoolCold 
Please know that English is not my native language, and I may make some confusing mistakes.

Answer about install steps:
I think the same thing is needed. Because the shell used varies from person to person.

Answer about `Next question - does it support to work with "local" config. i.e. per directory? I don't see how it can be done, but just in case.`: 

"local" mean "asdf local" command ?

Thanks for asking the question!

**Comment by CoolCold** [comment]
>  Please know that English is not my native language, and I may make some confusing mistakes.

No worries, it's not native for me as well :)

> "local" mean "asdf local" command ?

yes

>  I think the same thing is needed. Because the shell used varies from person to person.

I see. Then I think README should be extended to mention this. Reasoning - I (and may be others) expect that after applying plugin install, it would be available, while this is not the case here and needs some manual actions to be done.

**Comment by gr1m0h** [comment]
> Then I think README should be extended to mention this. Reasoning - I (and may be others) expect that after applying plugin install, it would be available, while this is not the case here and needs some manual actions to be done.

OK. I will make a PR. So, could you please review it?

I didn't even consider about local command.
Please wait for a while as I will check the operation.

**Comment by gr1m0h** [comment]
@CoolCold 

Answer about `does it support to work with "local" config. i.e. per directory? I don't see how it can be done, but just in case.` :

Confirmed that the local command is available as follows.

```
asdf-starship > asdf local  starship 0.40.1
asdf-starship > asdf global starship 0.47.0
asdf-starship > starship --version
starship 0.40.1
asdf-starship > cd
~ > starship --version
starship 0.47.0
```
